### PR TITLE
disable headless auto form filling

### LINKED ISSUE #876: Katana JSONL file Issue on `raw` request field
Katana JSONL file has issues on saving `POST` requests, for Example:
```
{"timestamp":"2024-05-02T16:28:07.690561274Z","request":{"method":"POST","endpoint":"http://testphp.vulnweb.com/secured/newuser.php","body":"signup=signup\u0026uuname=katana\u0026upass=katanaP@assw0rd1\u0026upass2=katanaP@assw0rd1\u0026urname=katana\u0026ucc=katana\u0026uemail=katana\u0026uphone=katana","headers":{"Content-Type":"application/x-www-form-urlencoded"},"tag":"form","attribute":"action","source":"http://testphp.vulnweb.com/signup.php","raw":"GET /secured/newuser.php HTTP/1.1\r\nHost: testphp.vulnweb.com\r\nUser-Agent: Go-http-client/1.1\r\nCookie: PHPSESSIONID=XXXXXXXXX\r\nHost-Header: hostname.tld\r\nX-Api-Key: XXXXX\r\nX-Powered-By: Raider\r\nAccept-Encoding: gzip\r\n\r\n"},"response":{"status_code":200,"headers":{"x_powered_by":"PHP/5.6.40-38+ubuntu20.04.1+deb.sury.org+1","content_encoding":"gzip","server":"nginx/1.19.0","date":"Thu, 02 May 2024 16:28:05 GMT","content_type":"text/html; charset=UTF-8","transfer_encoding":"chunked","connection":"keep-alive"},"body":"\u003chtml\u003e\u003chead\u003e\n\u003ctitle\u003eadd new user\u003c/title\u003e\n\u003cmeta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"\u003e\n\u003clink href=\"style.css\" rel=\"stylesheet\" type=\"text/css\"\u003e\n\u003c/head\u003e\n\u003cbody\u003e\n\u003cdiv id=\"masthead\"\u003e \n  \u003ch1 id=\"siteName\"\u003eACUNETIX ART\u003c/h1\u003e \n\u003c/div\u003e\n\u003cdiv id=\"content\"\u003e\n\t\u003c/div\u003e\n\n\n\u003c/body\u003e\u003c/html\u003e","technologies":["PHP:5.6.40","Nginx:1.19.0","Ubuntu"],"raw":"HTTP/1.1 200 OK\r\nContent-Length: 415\r\nConnection: keep-alive\r\nContent-Encoding: gzip\r\nContent-Type: text/html; charset=UTF-8\r\nDate: Thu, 02 May 2024 16:28:05 GMT\r\nServer: nginx/1.19.0\r\nX-Powered-By: PHP/5.6.40-38+ubuntu20.04.1+deb.sury.org+1\r\n\r\n\u003c!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"\u003e\r\n\u003chtml\u003e\r\n\u003chead\u003e\r\n\u003ctitle\u003eadd new user\u003c/title\u003e\r\n\u003cmeta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"\u003e\r\n\u003clink href=\"style.css\" rel=\"stylesheet\" type=\"text/css\"\u003e\r\n\u003c/head\u003e\r\n\u003cbody\u003e\r\n\u003cdiv id=\"masthead\"\u003e \r\n  \u003ch1 id=\"siteName\"\u003eACUNETIX ART\u003c/h1\u003e \r\n\u003c/div\u003e\r\n\u003cdiv id=\"content\"\u003e\r\n\t\u003c/div\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e\r\n"}}
```

but it seems OK in `GET` Requests:
```
{"timestamp":"2024-05-02T16:28:03.490823562Z","request":{"method":"GET","endpoint":"http://testphp.vulnweb.com/artists.php?artist=1","tag":"a","attribute":"href","source":"http://testphp.vulnweb.com/artists.php","raw":"GET /artists.php?artist=1 HTTP/1.1\r\nHost: testphp.vulnweb.com\r\nUser-Agent: Go-http-client/1.1\r\nCookie: PHPSESSIONID=XXXXXXXXX\r\nHost-Header: hostname.tld\r\nX-Api-Key: XXXXX\r\nX-Powered-By: Raider\r\nAccept-Encoding: gzip\r\n\r\n"},"response":{"status_code":200,"headers":{"server":"nginx/1.19.0","date":"Thu, 02 May 2024 16:28:01 GMT","content_type":"text/html; charset=UTF-8","transfer_encoding":"chunked","connection":"keep-alive","x_powered_by":"PHP/5.6.40-38+ubuntu20.04.1+deb.sury.org+1","content_encoding":"gzip"},"body":"\u003chtml\u003e\u003chead\u003e\u003c/head\u003e\u003cbody\u003eWarning: mysql_connect(): Connection refused in /hj/var/www/database_connect.php on line 2\nWebsite is out of order. Please visit back later. Thank you for understanding.\u003c/body\u003e\u003c/html\u003e","technologies":["PHP:5.6.40","Nginx:1.19.0","Ubuntu"],"raw":"HTTP/1.1 200 OK\r\nContent-Length: 170\r\nConnection: keep-alive\r\nContent-Encoding: gzip\r\nContent-Type: text/html; charset=UTF-8\r\nDate: Thu, 02 May 2024 16:28:01 GMT\r\nServer: nginx/1.19.0\r\nX-Powered-By: PHP/5.6.40-38+ubuntu20.04.1+deb.sury.org+1\r\n\r\n\nWarning: mysql_connect(): Connection refused in /hj/var/www/database_connect.php on line 2\nWebsite is out of order. Please visit back later. Thank you for understanding."}}
```

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes  #876

```console
```console
$ go run . -u http://testphp.vulnweb.com -hl -aff -j -o test.json
...

$ grep -r 'method":"POST"' test.json | grep -o '"raw":.*' | cut -c 1-50
"raw":"POST /search.php?test=query HTTP/1.1\r\nHos
"raw":"POST /search.php?test=query HTTP/1.1\r\nHos
"raw":"POST /userinfo.php HTTP/1.1\r\nHost: testph
"raw":"POST /userinfo.php HTTP/1.1\r\nHost: testph
"raw":"POST /secured/newuser.php HTTP/1.1\r\nHost:
"raw":"POST /secured/newuser.php HTTP/1.1\r\nHost:
"raw":"POST /guestbook.php HTTP/1.1\r\nHost: testp
"raw":"POST /guestbook.php HTTP/1.1\r\nHost: testp
```

### CODE REVIEW

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
It seems like we should review the proposed solution based upon https://github.com/projectdiscovery/katana/issues/876#issuecomment-2151797550. Probably form filling should be reconsidered/disabled as a whole for headless navigation as the way we are doing it is totally wrong, as it should happen via headless actions within the page context (ex. click on submit button).

**Comment by alban-stourbe-wmx** [comment]
Hello, 
Do you think it would be a good idea to create a function that automatically fills out forms using the rod package? 

Is it possible that for each request launched by page.Navigate, we search through xpaths/selector for forms and content to fill them again with predefined data and click? If this were possible, the request would be hijacked and we wouldn't have to filter requests by tag, and the navigateRequest function would suffice on its own.

I don't realize how hard it would be to add such a feature

**Comment by dogancanbakir** [comment]
Disabled headless auto form filling for now. I'll create a follow-up ticket to track this.

**Review by Mzack9999 — APPROVED** [review]

**Comment by alban-stourbe-wmx** [comment]
> hi @alban-stourbe-wmx Have you successfully solved this problem?

Hello @Miracles666, to fix the issue, the automatic-form has been disabled with headless mode. For my case, i detect forms with the option with the standard mode only.

If we really want to use automatic-form with headless mode, a new feature need to be develop to detect form and send data through the web browser. 

I hope you understand

**Comment by Miracles666** [comment]
@alban-stourbe-wmx  standard mode is very few things that can be crawled up ，I think this is a very serious bug。

**Comment by alban-stourbe-wmx** [comment]
> is very few things that can be crawled up

That's why if you think a bit, we can use the SDK Katana to crawl your website with the headless and the standard mode together. After you can merge and the two outputs to obtain all informations ;)

**Comment by Miracles666** [comment]
@alban-stourbe-wmx  can you share with me? thank you very much

**Comment by Miracles666** [comment]
@alban-stourbe-wmx  How to contact you outside of GitHub?

**Pull request merged**
