### PR TITLE
Add resolver in katana

### PR DESCRIPTION
**Pull request by ShubhamRasal**
eg: 
```
sudo ./tinydns -net udp -upstream 8.8.8.8:53
./katana -u https://projectdiscovery.io/ -r 127.0.0.1:53
```

### CODE REVIEW

**Review by Mzack9999 — APPROVED** [review]
-

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
The implementation lgtm - Anyway a few notes:
- Unfortunately we can't do much with native headless navigation, as custom resolver/mapping must be defined at startup time via `host-resolver-rules`
- With invalid resolvers, katana keeps working:
```console
$ cat resolver.txt 
10.10.11.10
$ ping 10.10.11.10
PING 10.10.11.10 (10.10.11.10): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
^C
$ echo http://projectdiscovery.io | go run . -resolvers resolver.txt 
...
https://projectdiscovery.io/
https://projectdiscovery.io/app.bundle.css
https://projectdiscovery.io/app.js
```

**Review by ehsandeep — APPROVED** [review]
```console
./tinydns -net udp -upstream 8.8.8.8:53

[INF] Listening on: udp:127.0.0.1:53
[INF] Received request for: docs.hackerone.com
[INF] Retrieving records for docs.hackerone.com with upstream 1.1.1.1:53.
[INF] Received request for: docs.hackerone.com
[INF] Retrieving records for docs.hackerone.com with upstream 8.8.8.8:53.
[INF] Saving records for docs.hackerone.com in cache.
[INF] Received request for: docs.hackerone.com
[INF] Received request for: docs.hackerone.com
[INF] Using cached record for docs.hackerone.com.
[INF] Received request for: docs.hackerone.com
```


```console
echo https://www.hackerone.com | ./katana -r 127.0.0.1

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/ v0.0.4-dev							 

		projectdiscovery.io

https://www.hackerone.com/events/rsa-conference-2023
https://www.hackerone.com/6th-annual-hacker-powered-security-report
https://www.hackerone.com/attack-resistance-assessment
https://www.hackerone.com/product/attack-surface-management
```

**Comment by ehsandeep** [comment]
Follow up tickets can be created for the above comments if needed.

**Pull request merged**
