### PR TITLE
introduce passive crawling

### LINKED ISSUE #139: Passive crawling from external sources support
### Please describe your feature request:
Add the ability to get passive URLs / endpoints from -

- [x] Wayback Machine (headless)
- [x] Common Crawl (headless)
- [ ] ~Virus Total~
- [x] Alien Vault
- [ ] ~URLScan~

**CLI Options -**

```console
   -ps, -passive                   enable passive sources to discover target endpoints
   -pss, -passive-source           passive source to use for url discovery (wayback,urlscan,commoncrawl,virustotal,alienvault)
```

**JSON Output -**

```json
{
  "timestamp": "2022-11-05T22:33:27.745815+05:30",
  "endpoint": "https://mail.google.com/mail/u/0/?ik=a9f1fef565&view=pt&search=all&permthid=thread-f:1717382568649591026",
  "source": "https://otx.alienvault.com/api/v1/indicators/domain/google.com/url_list?limit=100&page=5",
  "mode": "passive"
}
```

Example run:

```console
katana -u hackerone.com -passive -silent

https://hackerone.com/redirect?signature=147f892574d9bece120cd41a5c4539e3fa8e8066&url=https://vimeo.com/137725491
https://hackerone.com/teams/new
https://hackerone.com/sandbox
https://support.hackerone.com/hc/en-us/articles/211538803-Step-by-Step-How-to-write-a-good-vulnerability-report
https://www.hackerone.com/blog/H1-415-Recap-Oath-Pays-Over-400000-Hackers-One-Da%20y
https://hackerone.com/txt3rob
https://hackerone.com/redirect?signature=4d7211d04ad487ae4b5053792b10fe43badb57fe&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D5iRylyJTzWc
http://hackerone.com/googleplay
https://hackerone.com/reports/104543
https://hackerone.com/reports/83803
https://hackerone.com/reports/253558
https://hackerone.com/users/confirmation?confirmation_token=z1E1oUpkrMnuBQpMHDd
https://www.hackerone.com/product/challenge
https://www.hackerone.com/blog/Sikurs-COO-Hacker-Diversity-Essential-Securing-SIKURPhone
https://hackerone.com/reports/199438
https://hackerone.com/workday
http://api.hackerone.com:8880/
https://hackerone.com/redirect?signature=c8ae58718e901ab4b54c7bcab54b924cb07a386b&url=http://blog.innerht.ml/overflow-trilogy/
https://hackerone.com/reports/269831
http://www.hackerone.com:8880/
http://hackerone.com:8880/
https://hackerone.com/redirect?signature=0486c622361ef174ec407e000fd0f4e54bdaec4a&url=https://www.owasp.org/index.php?title=Broken_Authentication_and_Session_Management&setlang=en
https://hackerone.com/users/sign_up
https://hackerone.com/reports/223609
https://www.hackerone.com/sites/default/files/2018-07/The%20Hacker-Powered%20Security%20Report%202018.pdf
http://hackerone.com/w2w
http://api.hackerone.com:2083/
http://api.hackerone.com:443/
http://api.hackerone.com:8443/
https://hackerone.com/notifications
https://www.hackerone.com/blog/How-to-Hack-Get-Started-Hacking-Mobile
https://hackerone.com/spotify
https://hackerone.com/users/confirmation?confirmation_token=AxJjSSHbxLuxE2wsKrLz
https://www.hackerone.com/privacy
https://hackerone.com/bugs?subject=user&report_id=
https://hackerone.com/hacktivity
https://hackerone.com/reports/180074
https://hackerone.com/glasswire
https://www.hackerone.com/sites/default/files/2018-06/HackerOne-BlackHat-Vegas-Week-Activities-2018_0.pdf
https://hackerone.com/augurproject
https://hackerone.com/leaderboard/all-time
https://hackerone.com/uber
https://hackerone.com/reports/244504
https://hackerone.com/egyptghost1&amp;d=DwMFaQ&amp;c=7DfhQjPWzR3PmWBQVpi%kw&amp;r=nZr0nOaewW9j3jAt8xfGtw&amp;m=R1VVkSZXns7lMVewqXGum%CDerCjoWKII9VPm54%kyk&amp;s=unQflkqs62j/8P6jUmj6hUs5SNbLS8F53i0sZm4DZwE&amp;e=
https://hackerone.com/hacktivity?sort_type=popular&filter=type:all&page=1&range=forever
https://hackerone.com/gcheng
https://hackerone.com/jrjn
https://hackerone.com/spyboy
https://hackerone.com/dchan
```

**Note:**

1. In passive mode, all the applicable options like scope/filters, etc will be supported, except active crawling.
2. `-passive-source` option can specify single or multiple (comma-separated) sources.
3. as default, all supported passive sources will be used in passive mode.
4. passive crawling mode is optional, can be enabled with `-passive` flag.

### Describe the use case of this feature:
Katana's missing some important URLs compares to other crawler tools
```[tasklist]
### Tasks
- [ ] https://github.com/projectdiscovery/katana/issues/782
- [ ] https://github.com/projectdiscovery/katana/issues/783
- [ ] https://github.com/projectdiscovery/katana/issues/784
```

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #139

```console
go run . -u hackerone.com -ps

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/                                                   

                projectdiscovery.io

[INF] Current katana version v1.0.5 (latest)

https://hackerone.com/figdann
https://hackerone.com/0xf0e
https://hackerone.com/alerigord
https://hackerone.com/assets/static/main_js--0ks61pg.js
https://www.hackerone.com/company-news/introducing-program-levels-hacker-friendly-practices-improve-program-results
https://hackerone.com/davebb
https://www.hackerone.com/for-hackers/gtm.js
https://www.hackerone.com/application-security/how-industrys-first-hacker-powered-api-helps-hackers-automate-workflows
https://www.hackerone.com/core/themes/stable/css/system/components/progress.module.css?qdmjt3
https://hackerone.com/vampz
https://hackerone.com/bazookaa
https://hackerone.com/deep_aman_knp
https://hackerone.com/gosterweil
https://hackerone.com/navreet2514
https://hackerone.com/wutchumeanman
https://hackerone.com/yuri_almeida
https://hackerone.com/assets/static/js/main.ef92e845.js
https://hackerone.com/dingbat
https://hackerone.com/fotrosthefallenangel1087654321
https://hackerone.com/geetagirij01928374655647382910
https://hackerone.com/hack-us-h1c/hacktivity
https://hackerone.com/comehere123
https://hackerone.com/mastro_titta
https://hackerone.com/torproject?view_policy=true
https://hackerone.com/assets/constants-2a67188703cc082c42bcdb271bbbce028c0236e2dadb2792f73fb06898029882.js
https://hackerone.com/assets/frontend.71af6e628f7de0c794afe06389599db3.css
https://hackerone.com/assets/static/display_invitation_expiry-phs2ip__.js
https://hackerone.com/assets/static/js/main.3c6b6de1.js
https://hackerone.com/devinbileck
...

^C[INF] - Ctrl+C pressed in Terminal
[INF] Creating resume file: /Users/dogancanbakir/.config/katana/resume-cneqptna2ua0iajq0t3g.cfg

```

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
- [x] JSONL update to include passive information, we can use omitempty for `response` and `headers`.

```json
{
  "timestamp": "2024-03-02T02:12:06.977128+05:30",
  "request": {
    "method": "GET",
    "endpoint": "https://nuclei.projectdiscovery.io/tinyseg.min.js"
  },
  "response": {
    "headers": {}
  },
  "passive": {
    "source": "alienvault",
    "reference": "https://otx.alienvault.com/api/v1/indicators/domain/projectdiscovery.io/url_list?page=20"
  }
}
```
- [x] URL dedup, as of now duplicate lines are being returned in CLI and JSONL output.
- [x] CLI option validation, i.e `-headless` and `-passive` can't be used together.
- [ ] Misc CLI updates
```
[INF] Enumerating passive endpoints for projectdiscovery.io
....
....
....
[INF] Found 2335 endpoints for projectdiscovery.io in 10 seconds (alienvault: 433, waybackurls: 1500, commoncrawl: 434)
```

**Comment by dogancanbakir** [comment]
```console
$ go run . -u hackerone.com -ps                

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/                                                   

                projectdiscovery.io

[INF] Current katana version v1.0.5 (latest)
[INF] Enumerating passive endpoints for https://hackerone.com
https://hackerone.com/reports/118582.json
http://hackerone.com/sh1yo
https://www.hackerone.com/cookies
https://hackerone.com/fetlife/hacktivity
https://hackerone.com/assets/static/main_js-vEWx0Z9c.js
https://hackerone.com/reports/508459
https://hackerone.com/reports/361438
...
[INF] Found 171036 endpoints for https://hackerone.com in 1m0.417674709s (alienvault: 1198, commoncrawl: 16274, waybackarchive: 153564)
```

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
I'm a bit dubious about passive crawling capabilities within an active crawler. Anyway, 
I would suggest the following changes:
- [ ] Replace `RegexUrlExtractor` with a package defined `regexp` and global method:
```console
package extractor

var re = regexp.MustCompile(...)
func Extract(...) ... { ... }
```
- [ ] With a passive result create a Response object with 200 status code, and populate it with potential additional data (headers, body, etc) returned by the various provider (in case there is anything else than just the bare URL) - Probably it would be enough to parse the URL and assign to response. In order to benefit from potential future changes in the output formatting logic.

What do you think?

**Comment by dogancanbakir** [comment]
I made the first change, but I'm unsure about the second one. If I make the change, it'll look like this.
```json
{
    "timestamp": "2024-03-11T11:54:05.711507+03:00",
    "request": {
        "method": "GET",
        "endpoint": "https://hackerone.com/reports/508459"
    },
    "response": {
        "status_code": 200,
        "headers": {},
        "body": "https://hackerone.com/reports/508459"
    },
    "passive": {
        "source": "alienvault",
        "reference": "https://otx.alienvault.com/api/v1/indicators/domain/hackerone.com/url_list?page=1"
    }
}
```
What do you say? @Mzack9999 @ehsandeep

**Comment by Mzack9999** [comment]
As the crawler is organized in a way that a request has a matching response, the existence of an URL within a passive source, probably means that there was a `GET` or `HEAD` request that received a `200` response (the body should remain empty, if not available from the third party source). Based on this assumtpion, I think that we should populate the following fields of `navigation response`:
```go
type Response struct {
	Resp               *http.Response    `json:"-"`// <------- http.Response{StatusCode: 200, URL: url.Parse(passiveURL)}
	...
	StatusCode         int               `json:"status_code,omitempty"` // <----- 200
	RootHostname       string            `json:"-"` // <---- Domain Name
        ...
}
```
I believe that this might be useful in existing uses as SDK as well as future integrations with other providers that provide additional data than the mere URL (for example headers, body, etc...)

**Review by Mzack9999 — APPROVED** [review]
lgtm - Hopefully mixing active/passive detection will not generate too much ambiguity

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
