### PR TITLE
add content len field

### LINKED ISSUE #1032: Bug: Missing content_length in JSON output if server response lacks Content-Length header
### Current Behavior:

When using Katana with JSON output mode, the `content_length` field is not present if the server response does not explicitly include the `Content-Length` header.

#### Example:

Command:
```
katana -u https://gmail.com -fs fqdn -j | grep content_length
```

Output:
```
   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/                  

                projectdiscovery.io

[INF] Current katana version v1.1.0 (latest)
[INF] Started standard crawling for => https://gmail.com
➜  ~ 
```

However, when piping the same URLs through HTTPX, the `content_length` field is populated even if the `Content-Length` header is absent.

#### Example with HTTPX:
Command:
```
katana -u https://gmail.com | httpx -j | grep content_length
```

Output:
```
{"timestamp":"2024-09-17T12:59:02.204112+02:00","cdn_name":"google","cdn_type":"cdn","url":"https://gmail.com","status_code":301,"content_length":230}
```

### Expected Behavior:

HTTPX handles missing `Content-Length` headers by calculating the content length from the response body, ensuring the `content_length` field is present in the JSON output. This behavior is achieved through logic like this:

```go
// if content length is not defined
if resp.ContentLength <= 0 {
	// check if it's in the header and convert to int
	if contentLength, ok := resp.Headers["Content-Length"]; ok && len(contentLength) > 0 {
		resp.ContentLength = strconv.Atoi(contentLength[0])
	}

	// use response body length if the content length is still zero
	if resp.ContentLength <= 0 && len(respbody) > 0 {
		resp.ContentLength = len(respbody)
	}
}
```

In contrast, Katana does not appear to include a similar mechanism for ensuring `content_length` is always provided.

#### Katana Code Snippets:

In `pkg/engine/standard/crawl.go`, Katana seems to set `resp.ContentLength` based solely on the response data length:
```go
resp.ContentLength = int64(len(data))
```

And in `pkg/navigation/response.go`, the `Response` struct doesn't include a `content_length` field:
```go
type Response struct {
	// Other fields
	StatusCode         int               `json:"status_code,omitempty"`
	Headers            Headers           `json:"headers,omitempty"`
	Body               string            `json:"body,omitempty"`
}
```

### Why This Matters:

The `content_length` field is essential for understanding the structure of a website’s response, particularly to identify whether the response body is empty. Including this data in the output helps users assess the content and size of a response even when the server omits the `Content-Length` header.

### Request:

Could you please add logic to Katana to calculate and include the `content_length` in the JSON output, similar to how HTTPX handles it? This would greatly improve the utility of Katana’s output when crawling websites without `Content-Length` headers.

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #1032

### CODE REVIEW

**Review by Mzack9999 — COMMENTED** [review]
From the issue, if the goal is mostly checking if the body is empty or not I think it's better to directly access it via `jq`, as the `Content-Length` header might be misleading  or inconsistent as well. For example:
```console
katana -u https://gmail.com | jq 'select(.body != "")'
```

What do you think?

**Comment by dogancanbakir** [comment]
Yes, but in this case, we're calculating the len from the body -mentioning @Sab0tag3d for the discussion.

**Comment by Sab0tag3d** [comment]
@Mzack9999 
Well, my goal is mostly to understand the size of the content on the pages. 
It's really helpful to detect some anomaly contents.

Besides, if we would use tool like jq, we need to store html bodies in report (in my case it's json file).
I don't do it because of space, in memory and on disk.
Also, sometimes JSON is broken because of body, and can't be parsed. I think it's because of maximum response size to read option, but haven't done investigation yet.

**Review by Mzack9999 — APPROVED** [review]
```console
% go run . -u https://scanme.sh -fs fqdn -j | grep content_length

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/                                                   

                projectdiscovery.io

[INF] Current katana version v1.1.0 (outdated)
[INF] Started standard crawling for => https://scanme.sh
{"timestamp":"2024-10-31T00:14:01.134533+01:00","request":{"method":"GET","endpoint":"https://scanme.sh","raw":"GET / HTTP/1.1\r\nHost: scanme.sh\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36\r\nAccept-Encoding: gzip\r\n\r\n"},"response":{"status_code":200,"headers":{"content-type":"text/plain; charset=utf-8","date":"Wed, 30 Oct 2024 23:14:00 GMT","content-length":"2"},"body":"ok","content_length":2,"raw":"HTTP/1.1 200 OK\r\nContent-Length: 2\r\nContent-Type: text/plain; charset=utf-8\r\nDate: Wed, 30 Oct 2024 23:14:00 GMT\r\n\r\nok"}}
```

**Pull request merged**
