### PR TITLE
Added path list input support for fuzzing and crawling

### PR DESCRIPTION
**Pull request by faf-xff**
```consoel
./katana -h path

Usage:
  ./katana [flags]

Flags:
   -path string  path or list of paths to use for fuzzing and crawling paths (comma-separated, file)
```

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
Thank you @faf-xff for this feature support.

Few things to confirm:
- [ ] Update path input support the same as httpx to support string, comma separated and file input.
- [ ] Ensuring endpoints getting extracted from fuzzed path responses.
- [ ] Path input support in headless engine

**Review by ehsandeep — CHANGES_REQUESTED** [review]
We can also add an option to disable default crawling so path-based crawling can perform more specific / known path-based crawling or crawl a couple of paths on target/internet. 

```console
   -ddc  -disable-default-crawl disable default automatic crawling
```

Example of performing specific path-based crawling -

```bash
$ katana -list targets.txt -path /app.js -ddc
$ katana -list targets.txt -path few_endpoints.txt -ddc
```

**Comment by tarunKoyalwar** [comment]
from what i can tell . we intentionally skipped using `retryablehttp` in katana . to avoid detections and other cipher fingerprinting etc  . this PR uses retryablehttp . we need to re-evalvate this since this is opposite of current behaviour??

- we can add support for `forced crawling` i.e start crawling with these paths . but not sure it is good idea to include fuzzing support in katana

cc: @ehsandeep  @Mzack9999

**Comment by ehsandeep** [comment]
> from what i can tell . we intentionally skipped using `retryablehttp` in katana . to avoid detections and other cipher fingerprinting etc . this PR uses retryablehttp . we need to re-evalvate this since this is opposite of current behaviour??
> 
> * we can add support for `forced crawling` i.e start crawling with these paths . but not sure it is good idea to include fuzzing support in katana
> 
> cc: @ehsandeep @Mzack9999

@tarunKoyalwar we can adapt the PR to make the code changes based on the above inputs.

**Comment by Mzack9999** [comment]
I don't think we should bring fuzzing and passive sources into katana, the tool is an active crawler. I think the same result can be obtained with something like this:
```console
echo target.host | httpx -path paths.txt | katana
```

**Comment by tarunKoyalwar** [comment]
@ehsandeep , as @Mzack9999 mentioned the usecase can be achieved just by using `httpx`

```console
httpx -list domains.txt -path paths.txt | katana
```
and this takes care of dead urls. so not sure idea proposed in PR

**Comment by Mzack9999** [comment]
@faf-xff I'm closing the PR as not planned since this functionality can be covered with faster processing via httpx and output piped to Katana. Please let me know if you think anything is missing. Thanks!

**Pull request closed without merging**
