### PR TITLE
ignore default paths if -scp is provided

### LINKED ISSUE #970: Cannot find the custom Chrome path when using both -sc and -scp options simultaneously.
### katana version:
Current version: v1.1.0

### Current Behavior:
If both `-sc` and `-scp` options are used simultaneously, it will exit directly if Chrome is not found in the default paths, even if the `-scp` option specifies the correct Chrome path.

### Expected Behavior:
The `-scp` specified Chrome path should take priority.

### PR DESCRIPTION
**Pull request by zrquan**
close #970

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks so much for your contribution @zrquan , we appreciate it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Review by dogancanbakir — APPROVED** [review]

**Comment by zrquan** [comment]
I accidentally deleted the head repository. Can someone teach me how to recover it, or do I have to submit a new PR :smiling_face_with_tear:

**Comment by dogancanbakir** [comment]
@zrquan  Can you create a new branch with the same name and commits?

**Comment by zrquan** [comment]
> create a new branch with the same name and commits

Then I created a new PR(#979) 😂

**Pull request closed without merging**
